//! Autogenerated weights
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2021-10-15, STEPS: `1`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 128

#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};
use frame_system::Config;

/// Concrete Weight Functions
pub struct WeightInfo<T>(PhantomData<T>);

impl<T> crate::pallet::WeightInfo for WeightInfo<T>
where
    T: Config,
{
    /// ```text
    /// Storage: MantaPay TotalSupply (r:1 w:0)
    /// Storage: MantaPay Balances (r:2 w:2)
    /// ```
    fn transfer() -> Weight {
        (108_000_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(3 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }

    /// ```text
    /// Storage: MantaPay Balances (r:1 w:1)
    /// Storage: MantaPay UtxoSet (r:1 w:1)
    /// Storage: MantaPay ShardTrees (r:1 w:1)
    /// Storage: MantaPay UtxoSetOutputs (r:0 w:1)
    /// Storage: MantaPay Shards (r:0 w:1)
    /// ```
    fn mint() -> Weight {
        (103_351_000_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(3 as Weight))
            .saturating_add(T::DbWeight::get().writes(5 as Weight))
    }

    /// ```text
    /// Storage: MantaPay UtxoSetOutputs (r:2 w:2)
    /// Storage: MantaPay VoidNumberSet (r:2 w:2)
    /// Storage: MantaPay UtxoSet (r:2 w:2)
    /// Storage: MantaPay VoidNumberSetSize (r:1 w:1)
    /// Storage: MantaPay ShardTrees (r:2 w:2)
    /// Storage: MantaPay VoidNumberSetInsertionOrder (r:0 w:2)
    /// Storage: MantaPay Shards (r:0 w:2)
    /// ```
    fn private_transfer() -> Weight {
        (145_263_000_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(9 as Weight))
            .saturating_add(T::DbWeight::get().writes(13 as Weight))
    }

    /// ```text
    /// Storage: MantaPay UtxoSetOutputs (r:2 w:1)
    /// Storage: MantaPay VoidNumberSet (r:2 w:2)
    /// Storage: MantaPay UtxoSet (r:1 w:1)
    /// Storage: MantaPay VoidNumberSetSize (r:1 w:1)
    /// Storage: MantaPay ShardTrees (r:1 w:1)
    /// Storage: MantaPay Balances (r:1 w:1)
    /// Storage: MantaPay VoidNumberSetInsertionOrder (r:0 w:2)
    /// Storage: MantaPay Shards (r:0 w:1)
    /// ```
    fn reclaim() -> Weight {
        (122_321_000_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(8 as Weight))
            .saturating_add(T::DbWeight::get().writes(10 as Weight))
    }
}
